const tweetExample = {
    "created_at": "Mon Oct 03 05:10:28 +0000 2016",
    "id": 782810025337073700,
    "id_str": "782810025337073664",
    "text": "Living like I've got tomorrow and a terminal condition\nThat's the product when you multiply my mind with my ambitions",
    "truncated": false,
    "entities": {
      "hashtags": [],
      "symbols": [],
      "user_mentions": [],
      "urls": []
    },
    "source": "<a href=\"http://twitter.com\" rel=\"nofollow\">Twitter Web Client</a>",
    "in_reply_to_status_id": null,
    "in_reply_to_status_id_str": null,
    "in_reply_to_user_id": null,
    "in_reply_to_user_id_str": null,
    "in_reply_to_screen_name": null,
    "user": {
      "id": 4893573253,
      "id_str": "4893573253",
      "name": "Le Blackwell",
      "screen_name": "CodeBlackwell",
      "location": "San Francisco, CA",
      "description": "Whether I'm exploring new frameworks or continuing to master familiar ones, I jump at the opportunity to expand my skill set.",
      "url": null,
      "entities": {
        "description": {
          "urls": []
        }
      },
      "protected": false,
      "followers_count": 24,
      "friends_count": 69,
      "listed_count": 1,
      "created_at": "Thu Feb 11 17:07:47 +0000 2016",
      "favourites_count": 5,
      "utc_offset": null,
      "time_zone": null,
      "geo_enabled": false,
      "verified": false,
      "statuses_count": 15,
      "lang": "en",
      "contributors_enabled": false,
      "is_translator": false,
      "is_translation_enabled": false,
      "profile_background_color": "000000",
      "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
      "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
      "profile_background_tile": false,
      "profile_image_url": "http://pbs.twimg.com/profile_images/723667363611041792/mhvAEZN-_normal.jpg",
      "profile_image_url_https": "https://pbs.twimg.com/profile_images/723667363611041792/mhvAEZN-_normal.jpg",
      "profile_banner_url": "https://pbs.twimg.com/profile_banners/4893573253/1473030686",
      "profile_link_color": "10206B",
      "profile_sidebar_border_color": "000000",
      "profile_sidebar_fill_color": "000000",
      "profile_text_color": "000000",
      "profile_use_background_image": false,
      "has_extended_profile": false,
      "default_profile": false,
      "default_profile_image": false,
      "following": false,
      "follow_request_sent": false,
      "notifications": false,
      "translator_type": "none"
    },
    "geo": null,
    "coordinates": null,
    "place": null,
    "contributors": null,
    "is_quote_status": false,
    "retweet_count": 0,
    "favorite_count": 0,
    "favorited": false,
    "retweeted": false,
    "lang": "en"
  }

  export default tweetExample